type UserProfile @aws_iam @aws_cognito_user_pools {
  name: String!
  email: String!
  phone: String
  role: String!
  locationJson: String
  trustScore: Float
  joinedAt: String!
  avatar: String
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owner: String
}

type Product @aws_iam @aws_cognito_user_pools {
  name: String!
  category: String!
  description: String
  unit: String!
  retailPrice: Float!
  bulkPrice: Float!
  bulkMinimum: Int!
  storeJson: String!
  available: Boolean
  image: String
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

type Pledge @aws_iam @aws_cognito_user_pools {
  userId: String!
  productId: String!
  productSnapshotJson: String!
  quantity: Int!
  unitPrice: Float!
  totalAmount: Float!
  maxAmount: Float!
  status: String!
  orderId: String
  lockedAt: String
  completedAt: String
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owner: String
}

type BulkOrder @aws_iam @aws_cognito_user_pools {
  productId: String!
  productSnapshotJson: String!
  totalQuantity: Int!
  targetQuantity: Int!
  pricePerUnit: Float!
  status: String!
  cutoffTime: String!
  executedAt: String
  runnerId: String
  dropZoneJson: String
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

input AmplifyAIConversationTurnErrorInput {
  errorType: String!
  message: String!
}

input ModelStringInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

input ModelIntInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelFloatInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  between: [Float]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelBooleanInput {
  ne: Boolean
  eq: Boolean
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelIDInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

input ModelSubscriptionStringInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
  in: [String]
  notIn: [String]
}

input ModelSubscriptionIntInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
  in: [Int]
  notIn: [Int]
}

input ModelSubscriptionFloatInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  between: [Float]
  in: [Float]
  notIn: [Float]
}

input ModelSubscriptionBooleanInput {
  ne: Boolean
  eq: Boolean
}

input ModelSubscriptionIDInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
  in: [ID]
  notIn: [ID]
}

enum ModelAttributeTypes {
  binary
  binarySet
  bool
  list
  map
  number
  numberSet
  string
  stringSet
  _null
}

input ModelSizeInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
}

enum ModelSortDirection {
  ASC
  DESC
}

type ModelUserProfileConnection @aws_iam @aws_cognito_user_pools {
  items: [UserProfile]!
  nextToken: String
}

input ModelUserProfileFilterInput {
  name: ModelStringInput
  email: ModelStringInput
  phone: ModelStringInput
  role: ModelStringInput
  locationJson: ModelStringInput
  trustScore: ModelFloatInput
  joinedAt: ModelStringInput
  avatar: ModelStringInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelUserProfileFilterInput]
  or: [ModelUserProfileFilterInput]
  not: ModelUserProfileFilterInput
  owner: ModelStringInput
}

type Query {
  getUserProfile(id: ID!): UserProfile @aws_iam @aws_cognito_user_pools
  listUserProfiles(filter: ModelUserProfileFilterInput, limit: Int, nextToken: String): ModelUserProfileConnection @aws_iam @aws_cognito_user_pools
  getProduct(id: ID!): Product @aws_iam @aws_cognito_user_pools
  listProducts(filter: ModelProductFilterInput, limit: Int, nextToken: String): ModelProductConnection @aws_iam @aws_cognito_user_pools
  getPledge(id: ID!): Pledge @aws_iam @aws_cognito_user_pools
  listPledges(filter: ModelPledgeFilterInput, limit: Int, nextToken: String): ModelPledgeConnection @aws_iam @aws_cognito_user_pools
  getBulkOrder(id: ID!): BulkOrder @aws_iam @aws_cognito_user_pools
  listBulkOrders(filter: ModelBulkOrderFilterInput, limit: Int, nextToken: String): ModelBulkOrderConnection @aws_iam @aws_cognito_user_pools
}

input ModelUserProfileConditionInput {
  name: ModelStringInput
  email: ModelStringInput
  phone: ModelStringInput
  role: ModelStringInput
  locationJson: ModelStringInput
  trustScore: ModelFloatInput
  joinedAt: ModelStringInput
  avatar: ModelStringInput
  and: [ModelUserProfileConditionInput]
  or: [ModelUserProfileConditionInput]
  not: ModelUserProfileConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  owner: ModelStringInput
}

input CreateUserProfileInput {
  name: String!
  email: String!
  phone: String
  role: String!
  locationJson: String
  trustScore: Float
  joinedAt: String!
  avatar: String
  id: ID
}

input UpdateUserProfileInput {
  name: String
  email: String
  phone: String
  role: String
  locationJson: String
  trustScore: Float
  joinedAt: String
  avatar: String
  id: ID!
}

input DeleteUserProfileInput {
  id: ID!
}

type Mutation {
  createUserProfile(input: CreateUserProfileInput!, condition: ModelUserProfileConditionInput): UserProfile @aws_iam @aws_cognito_user_pools
  updateUserProfile(input: UpdateUserProfileInput!, condition: ModelUserProfileConditionInput): UserProfile @aws_iam @aws_cognito_user_pools
  deleteUserProfile(input: DeleteUserProfileInput!, condition: ModelUserProfileConditionInput): UserProfile @aws_iam @aws_cognito_user_pools
  createProduct(input: CreateProductInput!, condition: ModelProductConditionInput): Product @aws_iam @aws_cognito_user_pools
  updateProduct(input: UpdateProductInput!, condition: ModelProductConditionInput): Product @aws_iam @aws_cognito_user_pools
  deleteProduct(input: DeleteProductInput!, condition: ModelProductConditionInput): Product @aws_iam @aws_cognito_user_pools
  createPledge(input: CreatePledgeInput!, condition: ModelPledgeConditionInput): Pledge @aws_iam @aws_cognito_user_pools
  updatePledge(input: UpdatePledgeInput!, condition: ModelPledgeConditionInput): Pledge @aws_iam @aws_cognito_user_pools
  deletePledge(input: DeletePledgeInput!, condition: ModelPledgeConditionInput): Pledge @aws_iam @aws_cognito_user_pools
  createBulkOrder(input: CreateBulkOrderInput!, condition: ModelBulkOrderConditionInput): BulkOrder @aws_iam @aws_cognito_user_pools
  updateBulkOrder(input: UpdateBulkOrderInput!, condition: ModelBulkOrderConditionInput): BulkOrder @aws_iam @aws_cognito_user_pools
  deleteBulkOrder(input: DeleteBulkOrderInput!, condition: ModelBulkOrderConditionInput): BulkOrder @aws_iam @aws_cognito_user_pools
}

input ModelSubscriptionUserProfileFilterInput {
  name: ModelSubscriptionStringInput
  email: ModelSubscriptionStringInput
  phone: ModelSubscriptionStringInput
  role: ModelSubscriptionStringInput
  locationJson: ModelSubscriptionStringInput
  trustScore: ModelSubscriptionFloatInput
  joinedAt: ModelSubscriptionStringInput
  avatar: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionUserProfileFilterInput]
  or: [ModelSubscriptionUserProfileFilterInput]
  owner: ModelStringInput
}

type Subscription {
  onCreateUserProfile(filter: ModelSubscriptionUserProfileFilterInput, owner: String): UserProfile @aws_subscribe(mutations: ["createUserProfile"]) @aws_iam @aws_cognito_user_pools
  onUpdateUserProfile(filter: ModelSubscriptionUserProfileFilterInput, owner: String): UserProfile @aws_subscribe(mutations: ["updateUserProfile"]) @aws_iam @aws_cognito_user_pools
  onDeleteUserProfile(filter: ModelSubscriptionUserProfileFilterInput, owner: String): UserProfile @aws_subscribe(mutations: ["deleteUserProfile"]) @aws_iam @aws_cognito_user_pools
  onCreateProduct(filter: ModelSubscriptionProductFilterInput): Product @aws_subscribe(mutations: ["createProduct"]) @aws_iam @aws_cognito_user_pools
  onUpdateProduct(filter: ModelSubscriptionProductFilterInput): Product @aws_subscribe(mutations: ["updateProduct"]) @aws_iam @aws_cognito_user_pools
  onDeleteProduct(filter: ModelSubscriptionProductFilterInput): Product @aws_subscribe(mutations: ["deleteProduct"]) @aws_iam @aws_cognito_user_pools
  onCreatePledge(filter: ModelSubscriptionPledgeFilterInput, owner: String): Pledge @aws_subscribe(mutations: ["createPledge"]) @aws_iam @aws_cognito_user_pools
  onUpdatePledge(filter: ModelSubscriptionPledgeFilterInput, owner: String): Pledge @aws_subscribe(mutations: ["updatePledge"]) @aws_iam @aws_cognito_user_pools
  onDeletePledge(filter: ModelSubscriptionPledgeFilterInput, owner: String): Pledge @aws_subscribe(mutations: ["deletePledge"]) @aws_iam @aws_cognito_user_pools
  onCreateBulkOrder(filter: ModelSubscriptionBulkOrderFilterInput): BulkOrder @aws_subscribe(mutations: ["createBulkOrder"]) @aws_iam @aws_cognito_user_pools
  onUpdateBulkOrder(filter: ModelSubscriptionBulkOrderFilterInput): BulkOrder @aws_subscribe(mutations: ["updateBulkOrder"]) @aws_iam @aws_cognito_user_pools
  onDeleteBulkOrder(filter: ModelSubscriptionBulkOrderFilterInput): BulkOrder @aws_subscribe(mutations: ["deleteBulkOrder"]) @aws_iam @aws_cognito_user_pools
}

type ModelProductConnection @aws_iam @aws_cognito_user_pools {
  items: [Product]!
  nextToken: String
}

input ModelProductFilterInput {
  name: ModelStringInput
  category: ModelStringInput
  description: ModelStringInput
  unit: ModelStringInput
  retailPrice: ModelFloatInput
  bulkPrice: ModelFloatInput
  bulkMinimum: ModelIntInput
  storeJson: ModelStringInput
  available: ModelBooleanInput
  image: ModelStringInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelProductFilterInput]
  or: [ModelProductFilterInput]
  not: ModelProductFilterInput
}

input ModelProductConditionInput {
  name: ModelStringInput
  category: ModelStringInput
  description: ModelStringInput
  unit: ModelStringInput
  retailPrice: ModelFloatInput
  bulkPrice: ModelFloatInput
  bulkMinimum: ModelIntInput
  storeJson: ModelStringInput
  available: ModelBooleanInput
  image: ModelStringInput
  and: [ModelProductConditionInput]
  or: [ModelProductConditionInput]
  not: ModelProductConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
}

input CreateProductInput {
  name: String!
  category: String!
  description: String
  unit: String!
  retailPrice: Float!
  bulkPrice: Float!
  bulkMinimum: Int!
  storeJson: String!
  available: Boolean
  image: String
  id: ID
}

input UpdateProductInput {
  name: String
  category: String
  description: String
  unit: String
  retailPrice: Float
  bulkPrice: Float
  bulkMinimum: Int
  storeJson: String
  available: Boolean
  image: String
  id: ID!
}

input DeleteProductInput {
  id: ID!
}

input ModelSubscriptionProductFilterInput {
  name: ModelSubscriptionStringInput
  category: ModelSubscriptionStringInput
  description: ModelSubscriptionStringInput
  unit: ModelSubscriptionStringInput
  retailPrice: ModelSubscriptionFloatInput
  bulkPrice: ModelSubscriptionFloatInput
  bulkMinimum: ModelSubscriptionIntInput
  storeJson: ModelSubscriptionStringInput
  available: ModelSubscriptionBooleanInput
  image: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionProductFilterInput]
  or: [ModelSubscriptionProductFilterInput]
}

type ModelPledgeConnection @aws_iam @aws_cognito_user_pools {
  items: [Pledge]!
  nextToken: String
}

input ModelPledgeFilterInput {
  userId: ModelStringInput
  productId: ModelStringInput
  productSnapshotJson: ModelStringInput
  quantity: ModelIntInput
  unitPrice: ModelFloatInput
  totalAmount: ModelFloatInput
  maxAmount: ModelFloatInput
  status: ModelStringInput
  orderId: ModelStringInput
  lockedAt: ModelStringInput
  completedAt: ModelStringInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelPledgeFilterInput]
  or: [ModelPledgeFilterInput]
  not: ModelPledgeFilterInput
  owner: ModelStringInput
}

input ModelPledgeConditionInput {
  userId: ModelStringInput
  productId: ModelStringInput
  productSnapshotJson: ModelStringInput
  quantity: ModelIntInput
  unitPrice: ModelFloatInput
  totalAmount: ModelFloatInput
  maxAmount: ModelFloatInput
  status: ModelStringInput
  orderId: ModelStringInput
  lockedAt: ModelStringInput
  completedAt: ModelStringInput
  and: [ModelPledgeConditionInput]
  or: [ModelPledgeConditionInput]
  not: ModelPledgeConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  owner: ModelStringInput
}

input CreatePledgeInput {
  userId: String!
  productId: String!
  productSnapshotJson: String!
  quantity: Int!
  unitPrice: Float!
  totalAmount: Float!
  maxAmount: Float!
  status: String!
  orderId: String
  lockedAt: String
  completedAt: String
  id: ID
}

input UpdatePledgeInput {
  userId: String
  productId: String
  productSnapshotJson: String
  quantity: Int
  unitPrice: Float
  totalAmount: Float
  maxAmount: Float
  status: String
  orderId: String
  lockedAt: String
  completedAt: String
  id: ID!
}

input DeletePledgeInput {
  id: ID!
}

input ModelSubscriptionPledgeFilterInput {
  userId: ModelSubscriptionStringInput
  productId: ModelSubscriptionStringInput
  productSnapshotJson: ModelSubscriptionStringInput
  quantity: ModelSubscriptionIntInput
  unitPrice: ModelSubscriptionFloatInput
  totalAmount: ModelSubscriptionFloatInput
  maxAmount: ModelSubscriptionFloatInput
  status: ModelSubscriptionStringInput
  orderId: ModelSubscriptionStringInput
  lockedAt: ModelSubscriptionStringInput
  completedAt: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionPledgeFilterInput]
  or: [ModelSubscriptionPledgeFilterInput]
  owner: ModelStringInput
}

type ModelBulkOrderConnection @aws_iam @aws_cognito_user_pools {
  items: [BulkOrder]!
  nextToken: String
}

input ModelBulkOrderFilterInput {
  productId: ModelStringInput
  productSnapshotJson: ModelStringInput
  totalQuantity: ModelIntInput
  targetQuantity: ModelIntInput
  pricePerUnit: ModelFloatInput
  status: ModelStringInput
  cutoffTime: ModelStringInput
  executedAt: ModelStringInput
  runnerId: ModelStringInput
  dropZoneJson: ModelStringInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelBulkOrderFilterInput]
  or: [ModelBulkOrderFilterInput]
  not: ModelBulkOrderFilterInput
}

input ModelBulkOrderConditionInput {
  productId: ModelStringInput
  productSnapshotJson: ModelStringInput
  totalQuantity: ModelIntInput
  targetQuantity: ModelIntInput
  pricePerUnit: ModelFloatInput
  status: ModelStringInput
  cutoffTime: ModelStringInput
  executedAt: ModelStringInput
  runnerId: ModelStringInput
  dropZoneJson: ModelStringInput
  and: [ModelBulkOrderConditionInput]
  or: [ModelBulkOrderConditionInput]
  not: ModelBulkOrderConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
}

input CreateBulkOrderInput {
  productId: String!
  productSnapshotJson: String!
  totalQuantity: Int!
  targetQuantity: Int!
  pricePerUnit: Float!
  status: String!
  cutoffTime: String!
  executedAt: String
  runnerId: String
  dropZoneJson: String
  id: ID
}

input UpdateBulkOrderInput {
  productId: String
  productSnapshotJson: String
  totalQuantity: Int
  targetQuantity: Int
  pricePerUnit: Float
  status: String
  cutoffTime: String
  executedAt: String
  runnerId: String
  dropZoneJson: String
  id: ID!
}

input DeleteBulkOrderInput {
  id: ID!
}

input ModelSubscriptionBulkOrderFilterInput {
  productId: ModelSubscriptionStringInput
  productSnapshotJson: ModelSubscriptionStringInput
  totalQuantity: ModelSubscriptionIntInput
  targetQuantity: ModelSubscriptionIntInput
  pricePerUnit: ModelSubscriptionFloatInput
  status: ModelSubscriptionStringInput
  cutoffTime: ModelSubscriptionStringInput
  executedAt: ModelSubscriptionStringInput
  runnerId: ModelSubscriptionStringInput
  dropZoneJson: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionBulkOrderFilterInput]
  or: [ModelSubscriptionBulkOrderFilterInput]
}
